apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: pravvich/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: pravvich/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: pravvich/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: pravvich/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

  local:
    push: false
manifests:
  rawYaml:
    - ./inf/k8s/*
deploy:
  kubectl: {}
