apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: pravvich/client
          env:
            - name: NEXT_PUBLIC_STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-pub-secret
                  key: NEXT_PUBLIC_STRIPE_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
