name: Run Node.js Tests

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ['auth', 'tickets']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ${{ matrix.directory }}/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('${{ matrix.directory }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install Dependencies
        run: |
          cd ${{ matrix.directory }}
          npm ci

      - name: Run Tests
        run: |
          cd ${{ matrix.directory }}
          npm run test -- --watchAll=false
